---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quay-perf-test-serviceaccount
rules:
- apiGroups: ["extensions", "apps", "batch", "security.openshift.io", "policy"]
  resources: ["deployments", "jobs", "pods", "services", "jobs/status", "podsecuritypolicies", "securitycontextconstraints"]
  verbs: ["use", "get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quay-perf-test-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quay-perf-test-serviceaccount
subjects:
- kind: ServiceAccount
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    quay-perf-test-component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-perf-test-component: redis
  template:
    metadata:
      labels:
        quay-perf-test-component: redis
    spec:
      containers:
      - name: redis-master
        image: registry.access.redhat.com/rhscl/redis-32-rhel7
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /var/lib/redis/data
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    quay-perf-test-component: redis-service
spec:
  ports:
    - port: 6379
  selector:
    quay-perf-test-component: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-perf-results
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: quay-perf-test-orchestrator-1
  labels:
    quay-perf-test-component: orchestrator
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: python
        image: quay.io/rh-ee-bbodapat/quay-load:es-optional-logfix
        securityContext:
          privileged: true
        imagePullPolicy: Always
        env:
          - name: QUAY_HOST
            value: "quay.apps.cluster-qsrst.dynamic2.redhatworkshops.io"
          - name: QUAY_PASSWORD
            value: "r5bLtJNaCpok"
          - name: QUAY_USERNAME
            value: "quayadmin"
          - name: QUAY_OAUTH_TOKEN
            value: "XDZL29eGUjVZRgaBo24F6fAPPumKivoWY1WRvmeL"
          - name: QUAY_ORG
            value: "test"
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: PUSH_PULL_IMAGE
            value: "quay.io/rh-ee-bbodapat/quay-load:es-optional-logfix"
          - name: PUSH_PULL_NUMBERS
            value: "2"
          - name: TARGET_HIT_SIZE
            value: "10000"
          - name: CUSTOM_BUILD_IMAGE
            value: "quay.apps.cluster-qsrst.dynamic2.redhatworkshops.io/test/quay-load:v1.1"
          - name: TEST_BATCH_SIZE
            value: "1"
          - name: CONCURRENCY
            value: "1"
          - name: TEST_NAMESPACE
            value: "test-quay"
          - name: TEST_PHASES
            value: "PUSH_PULL"
          - name: SKIP_PUSH
            value: "true"
          - name: TAGS
            value: "quay.apps.cluster-qsrst.dynamic2.redhatworkshops.io/test/quay-load:v1.1,quay.apps.cluster-qsrst.dynamic2.redhatworkshops.io/test/quay-load:latest"
        volumeMounts:
          - name: tmp-logs
            mountPath: /tmp/logs
          - name: results
            mountPath: /tmp/results
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
      volumes:
        - name: tmp-logs
          emptyDir: {}
        - name: results
          persistentVolumeClaim:
            claimName: quay-perf-results
